# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  # Replace the UUID placeholders below with values from your machine.
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" "e1000e" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-REPLACE-WITH-YOUR-ROOT-LUKS-UUID";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-REPLACE-WITH-YOUR-ROOT-LUKS-UUID".device = "/dev/disk/by-uuid/REPLACE-WITH-YOUR-ROOT-LUKS-UUID";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/REPLACE-WITH-YOUR-BOOT-UUID";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/efi" =
    { device = "/dev/disk/by-uuid/REPLACE-WITH-YOUR-EFI-UUID";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
