# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" "e1000e" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-71dd3371-da9d-4b41-8994-2f7d15a67ad6";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-71dd3371-da9d-4b41-8994-2f7d15a67ad6".device = "/dev/disk/by-uuid/71dd3371-da9d-4b41-8994-2f7d15a67ad6";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E88E-8007";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/efi" =
    { device = "/dev/disk/by-uuid/E934-4EE1";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
